#!/usr/bin/env bash
#Script to tranfer a file to the server

path="~/"
if [[ "$#" -eq 4 ]]; then
    scp -i $4 -o StrictHostKeyChecking=no $1 $3@$2:$path
else
    echo Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
fi
