#!/usr/bin/env bash
#configuration

apt-get -y update
apt-get -y install nginx
sudo echo "Holberton School"  > /var/www/html/index.nginx-debian.html
st="rewrite ^/redirect_me$ https://www.youtube.com/watch?v=D5iNHy7qPqk permanent;"
sudo sed -i "66i ${st}" /etc/nginx/sites-available/default
sudo service nginex start
