#!/usr/bin/env bash
# shellcheck disable=SC2154
# setup NGINX

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
cm="rewrite ^/redirect_me https://www.youtube.com/ permanent;"
sudo sed -i "66i $cm" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
err="\\\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html{\n\t\troot /var/www/html;\n\t\tinternal;\n\t}\n"
sudo sed -i "44i $err" /etc/nginx/sites-available/default
head="add_header X-Served-By \$hostname;"
sudo sed -i "60i $head" /etc/nginx/nginx.conf
sudo service nginx start
