#!/usr/bin/env bash
#Creates a file and catch signals
touch /var/run/holbertonscript.pid
echo "$$" > /var/run/holbertonscript.pid
trap 'echo "I hate the kill command";
     rm /var/run/holbertonscript.pid;
     exit' SIGTERM
trap 'rm /var/run/holbertonscript.pid;
     exit' SIGQUIT
trap 'echo Y U no love me?!' SIGINT
while 'true'; do
	echo "To infinity and beyond"
	sleep 2
    done
