#!/usr/bin/env bash
# This script prints "Holberton School" ten times
i=0
while [ "$i" -lt 10 ]; do
    if [ "$i" -ne 3 ] && [ "$i" -ne 7 ]; then
       echo "Holberton School"
    elif [ "$i" -eq 7 ]; then
	echo "good luck"
    else
	echo "bad luck"
    fi
    ((i++))
done
