#!/usr/bin/env bash
# This script prints "Holberton School" ten times
i=0
while [ "$i" -lt 13 ]; do
    echo "Hour: $i"
    j=1
    while [ "$j" -lt 60 ]; do
	echo "$j"
	((j++))
    done
    ((i++))
done
